name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
          
      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
      - name: Setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
        
      - name: Pack
        run: dotnet pack --no-build -o .
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Publish NPredicateBuilder
        run: dotnet nuget push NPredicateBuilder.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
        
      - name: Publish NPredicateBuilder.EF
        run: dotnet nuget push NPredicateBuilder.EF.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
  
