name: .NET

on:
  push:
    branches: [ master ]

env:
    NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
          
      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
      - name: Setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Restore
        run: dotnet restore
      
      - name: Build & Pack
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Publish NPredicateBuilder
        run: dotnet nuget push D:/a/n-predicate-builder/n-predicate-builder/source/NPredicateBuilder/bin/Debug/NPredicateBuilder.*.nupkg --source https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN
        
      - name: Publish NPredicateBuilder.EF
        run: dotnet nuget push D:/a/n-predicate-builder/n-predicate-builder/source/NPredicateBuilder.EF/bin/Debug/NPredicateBuilder.EF.*.nupkg --source https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN
  
