name: main

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.0.2
        with:
          connection-string-env-var: TEST_CONNECTION_STRING
          catalog: NPredicateBuilder.Tests
          extra-params: "TrustServerCertificate=true;"

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=branch

      - name: Pack
        run: dotnet pack --no-build -c Release -o .

      - name: Publish
        run: dotnet nuget push NPredicateBuilder.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
